# Generated by Django 4.1.7 on 2023-04-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlybird',
            name='instagram',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
