# Generated by Django 4.1.7 on 2023-04-18 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CampaignOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
            ],
        ),
    ]
