# Generated by Django 4.1.7 on 2023-04-19 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campaign_category_campaignoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.campaigncategory'),
        ),
    ]
