# Generated by Django 4.1.7 on 2023-04-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campaign_influencer_post_campaignvideo_campaignimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='before_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
