# Generated by Django 4.1.7 on 2023-04-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_earlybird_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlybird',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
