# Generated by Django 4.1.7 on 2023-04-19 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_campaigncategory_alter_campaign_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='api.campaigncategory')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='sub_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.campaignsubcategory'),
        ),
    ]
