# Generated by Django 4.1.7 on 2023-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campaignsubcategory_campaign_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
